### ISSUE TITLE
[Bootstrap] panel 적용이 안되는 현상

### ISSUE THREAD

**Issue by austinpark420** [JinwooPark94/foodfly-team4#10]
foodorder 페이지view 작업 시 panel이 적용되지 않아 defalt.less 파일에 import를 적용하였습니다.
작업하실 때 참고 부탁드립니다.
<img width="326" alt="screen shot 2018-04-06 at 1 47 25 pm" src="https://user-images.githubusercontent.com/35208965/38403879-54ead576-39a1-11e8-95f6-33e910c1bdca.png">
댓글 달아주시면 issues closed 하겠습니다 : )

**Comment by JinwooPark94** [comment]
네 확인하였습니다 ! 수고하셨습니다 !
