### ISSUE TITLE
[Routing] Path 설정 관련 이슈.

### ISSUE THREAD

**Issue by austinpark420** [JinwooPark94/foodfly-team4#14]
path로 설정되어 있는 retaurant uri으로 접속하면 홈페이지 body에 아무 내용이 없습니다!
<img width="486" alt="screen shot 2018-04-07 at 9 14 28 pm" src="https://user-images.githubusercontent.com/35208965/38454784-db18d1f4-3aa8-11e8-992f-7c878e65cef4.png">
<img width="430" alt="screen shot 2018-04-07 at 9 07 50 pm" src="https://user-images.githubusercontent.com/35208965/38454798-1f838c3a-3aa9-11e8-83f0-01a6f5cd98d1.png">

이 뿐만 아니라, src/foodfly/components 속해있는 대부분의 컴포넌트 또한 동일한 현상이 발생하고 있습니다.
리다이렉팅이 필요할 것 같은데 다른 분들은 어떻게 생각하시나요?

**Comment by JinwooPark94** [comment]
네 저도 이 부분 생각하고 있었습니다. 용민님 말씀대로 restaurant uri로 들어왔을 때 redirect 기능을 사용하여 각 component에 대표하는 주소로 하는게 좋을 것 같습니다 !

**Comment by JinwooPark94** [comment]
![routes](https://user-images.githubusercontent.com/35209016/38478553-710fe0d4-3bf4-11e8-90c8-586a6134904a.PNG)
말씀하신 부분 redirects 사용하여 해결완료하였습니다.
