### ISSUE TITLE
app.module에 BrowserAnimationsModule 추가 건의

### ISSUE THREAD

**Issue by simmh** [JinwooPark94/foodfly-team4#22]
BrowserAnimationsModule이 여러 컴포넌트에서 사용되는 방향이고,
현재 각 컴포넌트 모듈에 import를 하여 쓰고있는데 아예 공용으로 import 함이 어떨까요?

**Comment by JinwooPark94** [comment]
아주 좋은 의견입니다 😀 회원쪽만 사용한다고 생각하여 MemberModule에만 import 하였는데 다른 곳에서도 사용된다고 하면 저는 찬성입니다 !

**Comment by austinpark420** [comment]
제가 작업 중인 RestaurantModule에도 애니메이션 효과 활용하고 있습니다!
미현님 말씀주신 것처럼 공용에 import하는 것이 좋을 것 같습니다 👍

**Comment by JinwooPark94** [comment]
네! 다들 의견 감사합니다. 말씀해주신대로 확인해서 수정하겠습니다 😀

**Comment by JinwooPark94** [comment]
미현님께서 처리해주셔서 이슈 닫겠습니다 !
