### ISSUE TITLE
[module] restaurant.module parse error

### ISSUE THREAD

**Issue by austinpark420** [JinwooPark94/foodfly-team4#25]
메인 repo에서 pull을 받았는데 parse error가 나타났습니다.
<img width="552" alt="screen shot 2018-04-15 at 9 05 49 pm" src="https://user-images.githubusercontent.com/35208965/38778230-3f50705c-40f1-11e8-9327-023a0328544e.png">

코드를 확인해보니 foodfly/components/restaurant/restaurant.module.ts 이 하기와 같은데
어느 부분을 수정하면 될까요?!
<img width="703" alt="screen shot 2018-04-15 at 9 05 32 pm" src="https://user-images.githubusercontent.com/35208965/38778236-7c5024fc-40f1-11e8-973e-a6cf70d65053.png">

**Comment by simmh** [comment]
ReactiveFormsModule 이 import 안되서 나는 오류같은데요,
BrowserAnimationsModule은 메인 app.moduel에 옴겼고 ReactiveFormsModule를 추가했으니 아래부분이 맞는 것 같아요.

**Comment by austinpark420** [comment]
네 감사합니다. 확인했습니다 👍
