### ISSUE TITLE
[img] sprite-icon 추가 가능 문의

### ISSUE THREAD

**Issue by austinpark420** [JinwooPark94/foodfly-team4#28]
![sprite-icon](https://user-images.githubusercontent.com/35208965/38801334-7ff0cf40-41a4-11e8-8121-deb3e847169a.png)
주문표에 plus(+),minus(-) 활용해야 하는 데요.
상기의 sprite-icon.png 파일에 추가가 가능한가요?

**Comment by austinpark420** [comment]
가능하면 쓰레기통icon도 추가하면 좋을 것 같습니다 :grinning:

**Comment by JinwooPark94** [comment]
네 집에서 확인한 다음 적용하여 다음 커밋에 올리겠습니다 !

**Comment by JinwooPark94** [comment]
방금 sprite-icon.png에 모두 추가 완료하였습니다. pull로 받으신 후 사용하시면 될 것 같습니다 !
