### ISSUE TITLE
주문하기 페이지에서 메뉴리스트 이미지 중간정렬 안되는 현장

### ISSUE THREAD

**Issue by austinpark420** [JinwooPark94/foodfly-team4#50]
<img width="633" alt="screen shot 2018-04-23 at 12 27 50 pm" src="https://user-images.githubusercontent.com/35208965/39105590-c9608a2e-46f1-11e8-90e9-cca1280a8d24.png">

수정이 필요할 것 같습니다!!

**Comment by simmh** [comment]
수직정렬 말씀이신가요? 제 생각에는 메뉴 이미지가 탑쪽에 위치하는게 맞다고 생각하거든요.
