### ISSUE TITLE
결제하기 페이지 휴대폰 번호 처리

### ISSUE THREAD

**Issue by simmh** [JinwooPark94/foodfly-team4#62]
기존에는 인증만 되면 상관 없기 때문에 조건은 숫자여부 하나였습니다.
그러나 우리 DB는 +82-010-1234-1234형식으로 전화 번호를 받기 때문에
결제페이지에서 10자~ 11자를 받으려 합니다. 이에 대한 의견 부탁합니다.

**Comment by simmh** [comment]
현재 11자 고정 입니다.

**Comment by JinwooPark94** [comment]
10에서 11자가 괜찮을 것 같습니다.
