### ISSUE TITLE
[Angular] main-repo pull 후 로컬서버 오류 발생

### ISSUE THREAD

**Issue by austinpark420** [JinwooPark94/foodfly-team4#8]
<img width="463" alt="screen shot 2018-04-06 at 12 06 18 am" src="https://user-images.githubusercontent.com/35208965/38374347-5b15a304-392e-11e8-9430-b00ef032fd96.png">
상기 내용이 반영된 main-repo를 pull한 후 ng-serve 실행시 하기와 같은 오류가 발생했습니다.
<img width="1137" alt="screen shot 2018-04-05 at 11 55 21 pm" src="https://user-images.githubusercontent.com/35208965/38374399-7a953e74-392e-11e8-9030-280491f498ad.png">
확인 부탁드립니다.

**Comment by JinwooPark94** [comment]
아 죄송합니다. 이번에 로그인 기능을 넣으면서 angular2-jwt을 추가하였습니다. package.json 파일에 넣어 있으니 npm install 하시면 해결될거 같습니다.
![error](https://user-images.githubusercontent.com/35209016/38374823-aa3a11e4-392f-11e8-8c79-98f2ac8eebc2.PNG)

**Comment by austinpark420** [comment]
정상작동 합니다!~
감사합니다 : )
