### ISSUE TITLE
ShareModule과 AppModule 관련한 질문입니다.

### ISSUE THREAD

**Issue by JinwooPark94** [JinwooPark94/foodfly-team4#9]
현재 AppModule에 ShareModule import로 포함되어 있는데 ShareModule는 강사님이 말씀하신게 AppModule과 따로 구별해야한다고 말씀하신 기억이 있어서 ShareModule import를 AppModule에서 제거 시킬려고 하는데 어떻게 생각하시나요?

**Comment by JinwooPark94** [comment]
강사님이 설명해주신 자료입니다.
![issue](https://user-images.githubusercontent.com/35209016/38401448-c1e59d2a-3990-11e8-8d90-aeacd5cb62dc.PNG)

**Comment by austinpark420** [comment]
강사님이 말씀해주신대로 ShareModule을 AppModule에 import하는 것보다 필요한 기능 모듈에 각각 import하는 것이 좋을 것 같습니다!!

**Comment by simmh** [comment]
위 제시한 구조로 변경하신다면 다소 일정에 영향이 있겠지만 찬성입니다.

**Comment by JinwooPark94** [comment]
중간에 시간나면 이 부분은 처리하도록 하겠습니다 !
